version: '3.3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: python ./trickingtime/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
