# Generated by Django 3.2.4 on 2021-06-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(help_text='The code name of the Project, e.i. XYZ123', max_length=10, verbose_name='Code Name')),
                ('short_description', models.CharField(blank=True, help_text='A short description for the Project, e.i. Cooking Journey', max_length=69, verbose_name='Short Description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
