# Generated by Django 3.2.4 on 2021-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_name',
            field=models.CharField(help_text='The code name of the Project, e.i. XYZ123', max_length=10, unique=True, verbose_name='Code Name'),
        ),
    ]
