# Generated by Django 3.2.4 on 2021-06-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, verbose_name='Day')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Work Day',
                'verbose_name_plural': 'Work Days',
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(help_text='The hour and minutes in which the activity was started', verbose_name='Begin')),
                ('end_time', models.TimeField(blank=True, help_text='The hour and minutes in which the activity was ended', verbose_name='End')),
                ('duration', models.TimeField(blank=True, editable=False, help_text='The duration of time between begin and end', verbose_name='Duration')),
                ('duration_decimal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, verbose_name='Duration in Decimal')),
                ('description', models.CharField(help_text='A description for the activity Cooking| Making Soup with Mrs. Lovett', max_length=200, verbose_name='Description')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='work_time.workday')),
            ],
            options={
                'verbose_name': 'Work Entry',
                'verbose_name_plural': 'Work Entries',
            },
        ),
    ]
