# Generated by Django 3.2.4 on 2021-06-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('work_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
