# Generated by Django 3.2.4 on 2021-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0002_workentry_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.DateField(editable=False, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='end_time',
            field=models.TimeField(help_text='The hour and minutes in which the activity was ended', null=True, verbose_name='End'),
        ),
    ]
