# Generated by Django 3.2.4 on 2021-06-13 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_code_name'),
        ('work_time', '0005_auto_20210610_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='description',
            field=models.CharField(help_text='A description for the activity Cooking, e.i Making Soup with Mrs. Lovett', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration_decimal',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='The duration of time between begin and end in decimal hours', max_digits=3, null=True, verbose_name='Duration in Decimal'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
