# Generated by Django 3.2.4 on 2021-06-13 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0006_auto_20210613_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
